/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "PWM.h"
#include "giro1_aliases.h"
#include "giro1.h"
#include "giro2_aliases.h"
#include "giro2.h"
#include "spwm_aliases.h"
#include "spwm.h"
#include "Clock_1.h"
#include "timer_clock.h"
#include "Timer.h"
#include "UART_1.h"
#include "isr_Timer.h"
#include "sensorA_aliases.h"
#include "sensorA.h"
#include "sensorB_aliases.h"
#include "sensorB.h"
#include "signal_Input_aliases.h"
#include "signal_Input.h"
#include "isr_Vueltas.h"
#include "UART_1_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

